/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StopDto
 */
export interface StopDto {
    /**
     * 
     * @type {number}
     * @memberof StopDto
     */
    lineNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof StopDto
     */
    destination?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof StopDto
     */
    waitingTimes?: Array<number>;
}

/**
 * Check if a given object implements the StopDto interface.
 */
export function instanceOfStopDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StopDtoFromJSON(json: any): StopDto {
    return StopDtoFromJSONTyped(json, false);
}

export function StopDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StopDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lineNumber': !exists(json, 'lineNumber') ? undefined : json['lineNumber'],
        'destination': !exists(json, 'destination') ? undefined : json['destination'],
        'waitingTimes': !exists(json, 'waitingTimes') ? undefined : json['waitingTimes'],
    };
}

export function StopDtoToJSON(value?: StopDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lineNumber': value.lineNumber,
        'destination': value.destination,
        'waitingTimes': value.waitingTimes,
    };
}

